'use client';
import {useEffect,useMemo,useState} from 'react';
import {calculateCommission,EmployeeName} from '@/lib/calculations';
type Tx={id:string;reference:string;kind:'sale'|'expense';amount:number;description:string;status:string;employee?:{name:string};project?:{name:string};commission:number;allocation:Record<string,number>};
const roles:EmployeeName[]=['Richard','Anastasia','Jean-Claude','Kevin','Svetlana'];
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n||0);
export default function Home(){const [role,setRole]=useState<EmployeeName>('Svetlana');const [tab,setTab]=useState<'entry'|'approvals'|'summary'|'setup'>('summary');const [kind,setKind]=useState<'sale'|'expense'>('sale');const [amount,setAmount]=useState('');const [description,setDescription]=useState('');const [project,setProject]=useState('Project A');const [transactions,setTransactions]=useState<Tx[]>([]);const [message,setMessage]=useState('');const [employees,setEmployees]=useState<{id:string,name:string,telegram_user_id?:number}[]>([]);
 const load=async()=>{const r=await fetch('/api/transactions');if(r.ok){const j=await r.json();setTransactions(j.transactions??[])}}; const loadEmployees=async()=>{const r=await fetch('/api/employees');if(r.ok)setEmployees((await r.json()).employees??[])}; useEffect(()=>{load();loadEmployees()},[]);
 const approved=transactions.filter(t=>t.status==='approved'); const sales=approved.filter(t=>t.kind==='sale'); const expenses=approved.filter(t=>t.kind==='expense'); const totals=useMemo(()=>({sales:sales.reduce((s,t)=>s+Number(t.amount),0),commissions:sales.reduce((s,t)=>s+Number(t.commission),0),expenses:expenses.reduce((s,t)=>s+Number(t.amount),0)}),[transactions]);
 async function submit(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/transactions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role,kind,amount:Number(amount),description,project})});const j=await r.json();setMessage(r.ok?'Submitted for review':j.error??'Could not submit');if(r.ok){setAmount('');setDescription('');load()}}
 async function approve(id:string,status:'approved'|'rejected'){const r=await fetch('/api/transactions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({role,id,status})});setMessage(r.ok?'Approval saved':(await r.json()).error);load()}
 return <main className="min-h-screen"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><div><div className="label">Friends Included Ltd</div><h1 className="mt-1 text-3xl font-black tracking-tight">Finance cockpit<span className="text-coral">.</span></h1></div><div className="flex items-center gap-3"><span className="label">Demo role</span><select value={role} onChange={e=>setRole(e.target.value as EmployeeName)} className="rounded-lg border bg-white px-3 py-2">{roles.map(r=><option key={r}>{r}</option>)}</select></div></header>
 <div className="mx-auto max-w-7xl px-6 pb-10"><nav className="mb-6 flex flex-wrap gap-2">{[['summary','Overview'],['entry','New entry'],['approvals','Approvals'],['setup','Manager setup']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`btn ${tab===id?'bg-ink text-white':'bg-white'}`}>{label}</button>)}</nav>
 {message&&<div className="mb-4 rounded-lg bg-mint px-4 py-3 text-sm font-semibold">{message}</div>}
 {tab==='summary'&&<><section className="grid gap-4 md:grid-cols-4">{[['Approved sales',totals.sales],['Commissions',-totals.commissions],['Expenses',-totals.expenses],['Company result',totals.sales-totals.commissions-totals.expenses]].map(([l,v])=><div className="card p-5" key={l as string}><div className="label">{l}</div><div className="mt-3 text-2xl font-black">{money(v as number)}</div></div>)}</section><section className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div className="card p-6"><h2 className="text-xl font-black">Project performance</h2><div className="mt-5 space-y-4">{['Project A','Project B'].map(p=>{const ps=sales.filter(t=>t.project?.name===p).reduce((s,t)=>s+Number(t.amount),0);const pe=expenses.filter(t=>t.project?.name===p).reduce((s,t)=>s+Number(t.amount),0);const pc=sales.filter(t=>t.project?.name===p).reduce((s,t)=>s+Number(t.commission),0);return <div key={p} className="rounded-xl bg-sand p-4"><div className="flex justify-between font-bold"><span>{p}</span><span>{money(ps-pc-pe)}</span></div><div className="mt-2 text-sm text-slate-500">Sales {money(ps)} · Commission {money(pc)} · Expenses {money(pe)}</div></div>})}</div></div><div className="card p-6"><h2 className="text-xl font-black">Quick links</h2><div className="mt-5 space-y-2 text-sm"><a className="block rounded-lg bg-sand p-3 font-semibold" href={process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL||'#'}>↗ Telegram bot</a><a className="block rounded-lg bg-sand p-3 font-semibold" href={process.env.NEXT_PUBLIC_GOOGLE_SHEET_URL||'#'}>↗ Google Sheet</a><a className="block rounded-lg bg-sand p-3 font-semibold" href={process.env.NEXT_PUBLIC_GITHUB_URL||'#'}>↗ GitHub repository</a></div></div></section></>}
 {tab==='entry'&&<section className="card max-w-2xl p-6"><h2 className="text-xl font-black">Submit a transaction</h2><form onSubmit={submit} className="mt-5 space-y-4"><div className="flex gap-2">{(['sale','expense'] as const).map(k=><button type="button" key={k} onClick={()=>setKind(k)} className={`btn flex-1 ${kind===k?'bg-coral text-white':'bg-sand'}`}>{k}</button>)}</div><label className="block"><span className="label">Amount (€)</span><input required min="0.01" step="0.01" type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="block"><span className="label">Project</span><select value={project} onChange={e=>setProject(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option>Project A</option><option>Project B</option></select></label><label className="block"><span className="label">Description</span><input required value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>{kind==='sale'&&amount&&<div className="rounded-lg bg-mint p-3 text-sm">Commission pool: <b>{money(calculateCommission(Number(amount)).pool)}</b></div>}<button className="btn w-full bg-ink text-white">Submit for approval</button></form></section>}
 {tab==='approvals'&&<section className="card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Manager approval workspace</h2><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold">{role==='Svetlana'?'Manager access':'Read-only demo'}</span></div><div className="mt-5 space-y-3">{transactions.filter(t=>t.status==='pending').map(t=><div className="flex flex-col gap-3 rounded-xl bg-sand p-4 md:flex-row md:items-center md:justify-between" key={t.id}><div><div className="font-bold">{t.kind} · {money(Number(t.amount))}</div><div className="text-sm text-slate-500">{t.description} · {t.employee?.name} · {t.project?.name}</div></div><div className="flex gap-2"><button className="btn bg-mint" disabled={role!=='Svetlana'} onClick={()=>approve(t.id,'approved')}>Approve</button><button className="btn bg-white" disabled={role!=='Svetlana'} onClick={()=>approve(t.id,'rejected')}>Reject</button></div></div>)}{!transactions.some(t=>t.status==='pending')&&<p className="text-slate-500">No pending transactions.</p>}</div></section>}
 {tab==='setup'&&<section className="card max-w-2xl p-6"><h2 className="text-xl font-black">Manager setup</h2><p className="mt-2 text-sm text-slate-500">Link Telegram user IDs to fictional employees. Only Svetlana can save changes.</p><div className="mt-5 space-y-3">{employees.filter(e=>e.name!=='Svetlana').map(e=><div className="flex items-center gap-3" key={e.id}><span className="w-32 font-bold">{e.name}</span><input id={`tg-${e.id}`} defaultValue={e.telegram_user_id??''} placeholder="Telegram user ID" className="flex-1 rounded-lg border px-3 py-2"/><button disabled={role!=='Svetlana'} onClick={async()=>{const value=(document.getElementById(`tg-${e.id}`) as HTMLInputElement).value;const r=await fetch('/api/employees',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({role,id:e.id,telegram_user_id:Number(value)})});setMessage(r.ok?'Employee link saved':(await r.json()).error);loadEmployees()}} className="btn bg-ink text-white">Save</button></div>)}</div></section>}
 </div></main>}
